import web3 from './web3';

const address = '0xedDE46EB622be5F455b6d4B0D8022cCa0016397e';
const abi = [
  {
    "constant":false,
    "inputs":[{"name":"i","type":"uint256"}],
    "name":"finalize",
    "outputs":[],
    "payable":false,
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "constant":true,
    "inputs":[{"name":"","type":"address"}],
    "name":"approvers",
    "outputs":[{"name":"","type":"bool"}],
    "payable":false,
    "stateMutability":"view",
    "type":"function"
  },
  {
    "constant":true,"inputs":[],
    "name":"minimum",
    "outputs":[{"name":"","type":"uint256"}],
    "payable":false,
    "stateMutability":"view",
    "type":"function"
  },
  {
    "constant":true,
    "inputs":[],
    "name":"noOfContributes",
    "outputs":[{"name":"","type":"uint256"}],
    "payable":false,
    "stateMutability":"view",
    "type":"function"
  },
  {
    "constant":false,
    "inputs":[{"name":"description","type":"string"},
    {"name":"amount","type":"uint256"},
    {"name":"receiver","type":"address"}],
    "name":"createReq",
    "outputs":[],
    "payable":false,
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "constant":true,
    "inputs":[],
    "name":"owner",
    "outputs":[{"name":"","type":"address"}],
    "payable":false,
    "stateMutability":"view",
    "type":"function"
  },
  {
    "constant":true,
    "inputs":[{"name":"","type":"uint256"}],
    "name":"allRequests",
    "outputs":[{"name":"amount","type":"uint256"},
              {"name":"receiver","type":"address"},
              {"name":"description","type":"string"},
              {"name":"complete","type":"bool"},
              {"name":"numberOfApp","type":"uint256"}],
    "payable":false,
    "stateMutability":"view",
    "type":"function"
  },
  {
    "constant":false,
    "inputs":[],
    "name":"contribute",
    "outputs":[],
    "payable":true,
    "stateMutability":"payable",
    "type":"function"
  },
  {
    "constant":false,
    "inputs":[{"name":"i","type":"uint256"}],
    "name":"approveRequest",
    "outputs":[],
    "payable":false,
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[{"name":"_min","type":"uint256"}],
    "payable":false,
    "stateMutability":"nonpayable",
    "type":"constructor"
  }
];


export default new web3.eth.Contract(abi, address);
